CREATE SCHEMA "ROOT" ;

CREATE TABLE ROOT.IDENTITY_MANAGEMENT_TBL (
	DISPLAYNAME VARCHAR(100),
	EMAIL VARCHAR(100),
	"attributes" VARCHAR(100),
	UID VARCHAR(100) NOT NULL,
	CONSTRAINT IDENTITY_MANAGEMENT_TBL_PK PRIMARY KEY (UID),
	CONSTRAINT IDENTITY_MANAGEMENT_TBL_USER_DETAILS_FK FOREIGN KEY (UID) REFERENCES ROOT.USER_DETAILS(UID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IDENTITY_MANAGEMENT_TBL_UID_IDX ON ROOT.IDENTITY_MANAGEMENT_TBL (UID) ;

CREATE TABLE ROOT.USER_DETAILS (
	"user" VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	UID VARCHAR(100) NOT NULL,
	CONSTRAINT USER_DETAILS_PK PRIMARY KEY (UID)
) ;